# work_dir is NewUserPredict which has been defined at python code
# generate path
# Raw dataset
train_csv: "dataset/train.csv"
train_processed_csv: "dataset/train_processed.csv"
train_pt: "data_generate/train.pt"

# divided by udmap
train_unknown_csv: "dataset/train_unknown.csv"
train_unknown_pt: "data_generate/train_unknown.pt"

train_known_csv: 'dataset/train_known.csv'
train_known_pt: "data_generate/train_known.pt"

# Test dataset need to be predicted
test_csv: "dataset/test.csv"
test_processed_csv: "dataset/test_processed.csv"
test_pt: "data_generate/test.pt"

# some directory
model_save_path: "model/"
plt_save_path: "photo/"
result_save_path: "result/"

# web hook of wecom
we_com_webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a7f64d24-662b-46ba-bbaf-cdf3f6209727"

# train
<<<<<<< HEAD
input_size: 13
hidden_size1: 1024
=======
input_size: 22
hidden_size1: 4096
>>>>>>> Micros0ft
hidden_size2: 128
lr: 0.001
division_rate: 0.8
num_epochs: 1000
batch_size: 512